version: '3.3'

services:
  database:
    image: postgres:13
    environment: 
      - POSTGRES_DB=dbConsultant
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports: 
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql